# Generated by Django 4.0.4 on 2022-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_banana', '0021_remove_story_body_remove_story_des_story_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_pic', models.FileField(upload_to='events/')),
            ],
        ),
    ]
